<section>
	<h1>Registrati</h1>
	<form method="post" action="">
		<div class="formrow">
			<div class="formlabel">
				la tua email
			</div>
			<div class="formfield">
				<input />
			</div>
		</div>
		<div class="formrow">
			<div class="formlabel">
				password
			</div>
			<div class="formfield">
				<input type="password" />
			</div>
		</div>
		<div class="formrow">
			<div class="formlabel">
				conferma password
			</div>
			<div class="formfield">
				<input type="password" />
			</div>
		</div>
		<div class="formrow">
			<div class="formlabel">
			</div>
			<div class="formfield">
				<button>Invia</button>
			</div>
		</div>
	</form>
</section>